.github/workflows/deploy-customer.yml, .github/workflows/deploy-store-owner.yml, eatngo-customer-api/Dockerfile, eatngo-store-owner-api/Dockerfile
- ECS Fargate 구성하여 github action으로 빌드할 수 있도록 환경 구성
---
- Dockerfile 추가
- github action workflow 추가
---
- Docker 이미지 아키텍처를 ECS Fargate에서 요구하는 linux/amd64로 지정하기 위해 buildx를 사용했습니다. 다만 이 과정에서 QEMU 애뮬레이션 환경에서 gradle이 안정적으로 동작하지 않아, gradle 빌드는 로컬에서 수행하고 docker에서는 Jar만 복사하는 방식으로 구성했습니다
- 구성한파일 방식으로 github action을 작성했습니다.
---
#7 
---
빌드 성공(아직 alb는 붙이지 않음)
- 점주 : http://13.125.220.149:8081/swagger-ui/index.html
- 사용자 : http://3.34.139.111:8080/swagger-ui/index.html
---
- github action쪽을 실제로 돌려보지 않아 수정이 필요 할 수도 있습니다. 구성 확인해보시고 의아한 부분 있다면 말씀주세요
- 상기 이슈로 gradle 빌드를 docker에서 하지 않았는데, 이렇게 해도 괜찮을지 의견 부탁드립니다 (여담으로 gradle을 밖으로 빼니 확실히 속도는 빨라지긴 했습니다)
---
---
ECS 구성 관련 작업 노션 노트
- https://www.notion.so/ECS-1efd5beeb0c0801dba44d1282e22cf63?pvs=4
=> [chore] ECS Fargate 구성

.github/workflows/ci.yml
jdk 버전을 17 -> 21 로 변경합니다.
---
jdk 버전을 17 -> 21 로 변경합니다.
---
jdk 버전을 17 -> 21 로 변경합니다.
---
---
---
---
---
---
=> [fix] ci에서 jdk versions을 잘못 사용하고 있어 이를 수정합니다.

eatngo-store-owner-api/src/main/resources/application.yml
- Mongo, Redis 붙이면서 누락된 store-owner쪽 설정 추가
---
---
---
---
---
---
---
=> [feat] store-owner쪽 mongo, redis 설정 추가

eatngo-customer-api/src/main/resources/application.yml, eatngo-infra/src/main/kotlin/com/eatngo/store/rdb/entity/StoreJpaEntity.kt, eatngo-store-owner-api/src/main/resources/application.yml
---
---
---
---
---
---
---
---
=> [CHORE] modify ddl auto create to update

eatngo-core/src/main/kotlin/com/eatngo/common/constant/StoreEnum.kt, eatngo-store-owner-api/src/main/kotlin/com/eatngo/store/docs/request/StoreCreateRequestDocs.kt, eatngo-store-owner-api/src/main/kotlin/com/eatngo/store/docs/request/StoreUpdateRequestDocs.kt
매장 카테고리 필드 변경
---
데이터 상 매장 카테고리 필드가 COFFEE가 아니라 CAFE로 저장되어있어 코드 내 COFFEE -> CAFE로 변경
---
=> [FIX] 매장 카테고리 필드 변경

eatngo-core/src/main/kotlin/com/eatngo/common/exception/user/CustomerAddressException.kt, eatngo-core/src/main/kotlin/com/eatngo/common/type/Address.kt, eatngo-core/src/main/kotlin/com/eatngo/customer/domain/CustomerAddress.kt, eatngo-core/src/main/kotlin/com/eatngo/customer/dto/AddressCreateDto.kt, eatngo-core/src/main/kotlin/com/eatngo/customer/dto/CustomerAddressDto.kt, eatngo-core/src/main/kotlin/com/eatngo/search/domain/SearchStore.kt, eatngo-core/src/main/kotlin/com/eatngo/search/dto/SearchStoreResultDto.kt, eatngo-core/src/main/kotlin/com/eatngo/store/dto/StoreDto.kt, eatngo-customer-api/src/test/kotlin/com/eatngo/customer/CustomerAddressControllerTest.kt, eatngo-infra/src/main/kotlin/com/eatngo/customer/persistence/CustomerAddressPersistenceImpl.kt, eatngo-infra/src/main/kotlin/com/eatngo/customer/rdb/entity/CustomerAddressJpaEntity.kt, eatngo-infra/src/main/kotlin/com/eatngo/mongo/search/entity/SearchStoreEntity.kt, eatngo-infra/src/main/kotlin/com/eatngo/store/rdb/entity/StoreAddressJpaEntity.kt, eatngo-infra/src/main/kotlin/com/eatngo/store/rdb/entity/StoreJpaEntity.kt
---
---
---
---
---
---
---
---
=> [FEATURE] 프론트 요청에 따른 요청 프로퍼티 변경

eatngo-auth/src/main/kotlin/com/eatngo/auth/handler/OAuth2LoginSuccessHandler.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/handler/OAuth2SuccessPostProcessor.kt, eatngo-customer-api/src/main/kotlin/com/eatngo/auth/handler/CustomerOAuth2SuccessPostProcessor.kt, eatngo-store-owner-api/src/main/kotlin/com/eatngo/auth/handler/StoreOwnerOAuth2SuccessPostProcessor.kt
---
---
---
---
---
---
---
---
=> feature/redirect-store-owner 점주 로그인 시 가게가 없으면 리다이렉트 시키기

eatngo-core/src/main/kotlin/com/eatngo/store/domain/Store.kt
주문 validation 을 위한 domain 메서드 추가한 부분 수정 전 메서드로 올라가서 수정해서 재 커밋
=> [FEAT] 주문 validation 을 위한 domain 메서드 추가한 부분 수정 전 메서드로 올라가서 수정해서 재 커밋

eatngo-core/src/main/kotlin/com/eatngo/common/error/BusinessErrorCode.kt, eatngo-core/src/main/kotlin/com/eatngo/common/exception/review/ReviewException.kt, eatngo-core/src/main/kotlin/com/eatngo/review/infra/ReviewPersistence.kt, eatngo-core/src/main/kotlin/com/eatngo/review/service/ReviewService.kt, eatngo-core/src/main/kotlin/com/eatngo/review/usecase/CreateReviewUseCase.kt, eatngo-core/src/main/kotlin/com/eatngo/review/usecase/ReadReviewUseCase.kt, eatngo-core/src/main/kotlin/com/eatngo/review/usecase/ReadReviewsUseCase.kt, eatngo-customer-api/src/main/kotlin/com/eatngo/review/ReviewController.kt, eatngo-infra/src/main/kotlin/com/eatngo/order/rdb/repository/OrderRdbRepository.kt, eatngo-infra/src/main/kotlin/com/eatngo/review/persistence/ReviewPersistenceImpl.kt, eatngo-infra/src/main/kotlin/com/eatngo/review/rdb/repository/ReviewRdbRepository.kt, eatngo-store-owner-api/src/main/kotlin/com/eatngo/review/ReviewController.kt
---
---
---
---
---
---
---
---
=> 리뷰 목록 조회 및 단일 조회 기능 추가

eatngo-infra/src/main/kotlin/com/eatngo/review/rdb/entity/ReviewJpaEntity.kt
---
---
---
---
---
---
---
---
=> fix: review 에서 image 가 정상적으로 호출되도록 수정

eatngo-auth/src/main/kotlin/com/eatngo/auth/token/TokenProvider.kt
---
---
---
---
---
---
---
---
=> feature/redirect-cookie 쿠키에 domain 설정 수정

eatngo-customer-api/src/main/kotlin/com/eatngo/config/CustomerSwaggerConfig.kt, eatngo-store-owner-api/src/main/kotlin/com/eatngo/config/StoreOwnerSwaggerConfig.kt
---
---
---
---
---
---
---
---
=> doc/modify-id-requirement 인증용 인자 스웨거에서 숨기기

eatngo-auth/src/main/kotlin/com/eatngo/auth/config/SecurityConfig.kt, eatngo-customer-api/src/main/kotlin/com/eatngo/auth/OAuth2DocController.kt, eatngo-customer-api/src/main/kotlin/com/eatngo/store/controller/StoreController.kt, eatngo-store-owner-api/src/main/kotlin/com/eatngo/auth/OAuth2DocController.kt
---
---
---
---
---
---
---
---
=> feature/append-prefix /api/v1 붙이기

eatngo-auth/src/main/kotlin/com/eatngo/auth/dto/LoginCustomer.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/dto/LoginStoreOwner.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/dto/LoginUser.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/dto/LoginUserAccount.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/filter/JwtAuthenticationFilter.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/handler/OAuth2LoginSuccessHandler.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/token/TokenProvider.kt, eatngo-customer-api/src/test/kotlin/com/eatngo/helper/CustomerTestHelper.kt, eatngo-store-owner-api/src/test/kotlin/com/eatngo/store_owner/StoreOwnerControllerTest.kt
---
---
---
---
---
---
---
---
=> feature/modify-cookie-store 점주 / 고객 쿠키 저장 장소 분리

eatngo-auth/src/main/kotlin/com/eatngo/auth/handler/OAuth2SuccessPostProcessor.kt
Reverts InnerCircle-ICD3/o2o-BE#170
=> Revert "fix/cookieStoreLocation"

eatngo-auth/src/main/kotlin/com/eatngo/auth/dto/LoginCustomer.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/dto/LoginStoreOwner.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/dto/LoginUser.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/dto/LoginUserAccount.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/filter/JwtAuthenticationFilter.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/handler/OAuth2LoginSuccessHandler.kt, eatngo-auth/src/main/kotlin/com/eatngo/auth/token/TokenProvider.kt, eatngo-customer-api/src/test/kotlin/com/eatngo/helper/CustomerTestHelper.kt, eatngo-store-owner-api/src/test/kotlin/com/eatngo/store_owner/StoreOwnerControllerTest.kt
Reverts InnerCircle-ICD3/o2o-BE#168
=> Revert "feature/modify-cookie-store 점주 / 고객 쿠키 저장 장소 분리"

eatngo-infra/src/main/kotlin/com/eatngo/order/rdb/repository/OrderRdbRepository.kt
---
---
---
---
---
---
---
---
=> fix: @param 추가

eatngo-core/src/main/kotlin/com/eatngo/order/usecase/OrderCreateUseCase.kt
---
---
---
---
---
---
---
---
=> fix: 주문 생성 시 quantity 가 잘못 들어가는 이슈 수정

eatngo-core/src/main/kotlin/com/eatngo/search/event/SearchStoreEventListener.kt
---
---
---
---
---
---
---
---
=> bug: 캐시 동기화 문제 수정

eatngo-core/src/main/kotlin/com/eatngo/order/event/OrderStatusChangedEvent.kt
---
---
---
---
---
---
---
---
=> fix: Order가 Ready로 변경되었을 때 이벤트 발행하도록 수정

eatngo-infra/src/main/kotlin/com/eatngo/aws/s3/S3Service.kt
- 점주쪽 매장 업로드 수정
---
---
---
---
---
---
---
---
=> bug: 매장 업로드 오류 수정
